#!/usr/bin/env python3
"""
Master Script for Comprehensive PCAP Verification
Запуск всех задач независимой верификации PCAP-анализа

This script runs all the verification tasks mentioned in task 5 of fakeddisorder-ttl-fix spec.
"""

import os
import sys
import subprocess
import json
from datetime import datetime
from typing import Dict, List

class ComprehensivePcapVerificationRunner:
    """Master runner for all PCAP verification tasks"""
    
    def __init__(self):
        self.results = {
            "timestamp": datetime.now().isoformat(),
            "tasks_completed": [],
            "tasks_failed": [],
            "summary": {}
        }
    
    def check_prerequisites(self) -> Dict[str, bool]:
        """Check if required files and tools are available"""
        prerequisites = {
            "zapret.pcap": os.path.exists("zapret.pcap"),
            "out2.pcap": os.path.exists("out2.pcap"),
            "python": True,  # We're running Python
        }
        
        # Check for optional dependencies
        try:
            import scapy
            prerequisites["scapy"] = True
        except ImportError:
            prerequisites["scapy"] = False
        
        try:
            import windivert
            prerequisites["windivert"] = True
        except ImportError:
            prerequisites["windivert"] = False
        
        return prerequisites
    
    def run_task(self, task_name: str, script_name: str, description: str) -> Dict:
        """Run a single verification task"""
        print(f"\n{'='*60}")
        print(f"RUNNING TASK: {task_name}")
        print(f"Description: {description}")
        print(f"Script: {script_name}")
        print(f"{'='*60}")
        
        task_result = {
            "task_name": task_name,
            "script_name": script_name,
            "description": description,
            "start_time": datetime.now().isoformat(),
            "success": False,
            "output": "",
            "error": "",
            "files_generated": []
        }
        
        try:
            # Run the script
            result = subprocess.run([
                sys.executable, script_name
            ], capture_output=True, text=True, timeout=300)  # 5 minute timeout
            
            task_result["output"] = result.stdout
            task_result["error"] = result.stderr
            task_result["return_code"] = result.returncode
            task_result["success"] = result.returncode == 0
            
            if task_result["success"]:
                print(f"✓ Task {task_name} completed successfully")
                self.results["tasks_completed"].append(task_name)
            else:
                print(f"✗ Task {task_name} failed with return code {result.returncode}")
                print(f"Error: {result.stderr}")
                self.results["tasks_failed"].append(task_name)
            
            # Check for generated files
            expected_files = self.get_expected_files(script_name)
            for file_path in expected_files:
                if os.path.exists(file_path):
                    task_result["files_generated"].append(file_path)
                    print(f"  Generated: {file_path}")
            
        except subprocess.TimeoutExpired:
            task_result["error"] = "Task timed out after 5 minutes"
            print(f"✗ Task {task_name} timed out")
            self.results["tasks_failed"].append(task_name)
        except Exception as e:
            task_result["error"] = str(e)
            print(f"✗ Task {task_name} failed with exception: {e}")
            self.results["tasks_failed"].append(task_name)
        
        task_result["end_time"] = datetime.now().isoformat()
        return task_result
    
    def get_expected_files(self, script_name: str) -> List[str]:
        """Get list of files expected to be generated by each script"""
        file_mappings = {
            "comprehensive_pcap_verification.py": [
                "pcap_verification_results.json",
                "pcap_verification_report.txt",
                "zapret_packet_1.bin",
                "recon_packet_1.bin",
                "zapret_packet_2.bin",
                "recon_packet_2.bin"
            ],
            "hex_pcap_analyzer.py": [
                "hex_pcap_analysis_results.json",
                "hex_pcap_analysis_report.txt",
                "zapret_packet_1_raw.hex",
                "recon_packet_1_raw.hex"
            ],
            "clean_packet_sender.py": [
                "clean_packet_experiment_results.json",
                "clean_packet_experiment_report.txt",
                "extracted_packet.bin"
            ]
        }
        return file_mappings.get(script_name, [])
    
    def run_all_verification_tasks(self):
        """Run all PCAP verification tasks"""
        print("COMPREHENSIVE PCAP VERIFICATION SUITE")
        print("=" * 80)
        print("This suite implements all sub-tasks from task 5 of fakeddisorder-ttl-fix spec:")
        print("- Независимая верификация PCAP-анализа")
        print("- Побайтовое сравнение IP и TCP заголовков")
        print("- Глубокий анализ TCP Options")
        print("- Охота на TCP Retransmission от ОС")
        print("- Анализ реакции на инъекцию")
        print("- Эксперимент с 'чистой' отправкой")
        print("=" * 80)
        
        # Check prerequisites
        print("\nChecking prerequisites...")
        prerequisites = self.check_prerequisites()
        for item, available in prerequisites.items():
            status = "✓" if available else "✗"
            print(f"  {status} {item}")
        
        if not prerequisites["zapret.pcap"]:
            print("\nERROR: zapret.pcap not found!")
            print("Please ensure zapret.pcap is in the current directory.")
            return
        
        if not prerequisites["out2.pcap"]:
            print("\nERROR: out2.pcap not found!")
            print("Please ensure out2.pcap is in the current directory.")
            return
        
        # Define tasks to run
        tasks = [
            {
                "name": "Comprehensive PCAP Analysis",
                "script": "comprehensive_pcap_verification.py",
                "description": "Scapy-based detailed packet analysis with timing, retransmission, and RST detection"
            },
            {
                "name": "Hex-level PCAP Analysis", 
                "script": "hex_pcap_analyzer.py",
                "description": "Raw binary packet analysis without Scapy dependency"
            },
            {
                "name": "Clean Packet Sending Experiment",
                "script": "clean_packet_sender.py", 
                "description": "Extract and send exact packet copy to test raw socket mechanism"
            }
        ]
        
        # Run each task
        task_results = []
        for task in tasks:
            if os.path.exists(task["script"]):
                result = self.run_task(task["name"], task["script"], task["description"])
                task_results.append(result)
            else:
                print(f"\nWARNING: Script {task['script']} not found, skipping task {task['name']}")
        
        # Generate summary
        self.generate_summary(task_results)
        
        # Save master results
        self.results["task_results"] = task_results
        with open("comprehensive_verification_master_results.json", 'w', encoding='utf-8') as f:
            json.dump(self.results, f, indent=2, ensure_ascii=False)
        
        print(f"\nMaster results saved to comprehensive_verification_master_results.json")
    
    def generate_summary(self, task_results: List[Dict]):
        """Generate summary of all verification tasks"""
        print(f"\n{'='*80}")
        print("VERIFICATION SUITE SUMMARY")
        print(f"{'='*80}")
        
        total_tasks = len(task_results)
        successful_tasks = len(self.results["tasks_completed"])
        failed_tasks = len(self.results["tasks_failed"])
        
        print(f"Total tasks run: {total_tasks}")
        print(f"Successful: {successful_tasks}")
        print(f"Failed: {failed_tasks}")
        print("")
        
        if successful_tasks > 0:
            print("✓ COMPLETED TASKS:")
            for task in self.results["tasks_completed"]:
                print(f"  - {task}")
            print("")
        
        if failed_tasks > 0:
            print("✗ FAILED TASKS:")
            for task in self.results["tasks_failed"]:
                print(f"  - {task}")
            print("")
        
        # List all generated files
        all_files = []
        for result in task_results:
            all_files.extend(result.get("files_generated", []))
        
        if all_files:
            print("📁 GENERATED FILES:")
            for file_path in all_files:
                size = os.path.getsize(file_path) if os.path.exists(file_path) else 0
                print(f"  - {file_path} ({size} bytes)")
            print("")
        
        # Overall assessment
        print("OVERALL ASSESSMENT:")
        print("-" * 40)
        
        if successful_tasks == total_tasks:
            print("✓ All verification tasks completed successfully!")
            print("  You now have comprehensive analysis of zapret.pcap vs out2.pcap")
            print("  Review the generated reports for detailed findings.")
        elif successful_tasks > 0:
            print(f"⚠ {successful_tasks}/{total_tasks} tasks completed successfully")
            print("  Partial analysis available - review successful task outputs")
        else:
            print("✗ All verification tasks failed")
            print("  Check error messages and prerequisites")
        
        # Recommendations
        print("\nRECOMMENDATIONS:")
        print("-" * 40)
        print("1. Review all generated .txt report files for human-readable analysis")
        print("2. Examine .json result files for detailed data")
        print("3. Use .hex and .bin files for manual hex editor inspection")
        print("4. Compare findings with existing pcap_inspect.py results")
        print("5. Focus on any detected timing issues or OS retransmissions")
        
        self.results["summary"] = {
            "total_tasks": total_tasks,
            "successful_tasks": successful_tasks,
            "failed_tasks": failed_tasks,
            "generated_files": all_files,
            "overall_success": successful_tasks == total_tasks
        }

def main():
    """Main function"""
    runner = ComprehensivePcapVerificationRunner()
    runner.run_all_verification_tasks()

if __name__ == "__main__":
    main()